p2pv2/config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root			  'static_pages#index'
  get  'howtoborrow' 	=>'static_pages#howtoborrow'
  get  'howtolend' 	=>'static_pages#howtolend'

  get 'search_items'	=>'items#index'

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'edit_user', to: 'devise/registrations#edit'
  end

  resources :users
  get 'users/index'  

  resources :items
  get 'items/index'

  resources :contracts
  get 'contracts/index'
  get 'contracts'    =>'contracts#index'
  put 'initiate'    =>'contracts#initiate'
  put 'returned'    =>'contracts#returned'

 

end

p2pv2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--Bootstrap template used was "http://startbootstrap.com/template-overviews/agency/"-->
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Custom Fonts -->
  <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body id="page-top" class="index">

  <!-- Navigation -->
  <nav id="home" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("BorrowLogo2.png", :class =>"borrow-logo" ), root_path,:class => "navbar-brand page-scroll" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li>
            <a class="page-scroll yellow" href="<%= root_path %>#how">How It Works</a>
          </li>
          <li>
            <a class="page-scroll yellow" href="<%= root_path %>#team">Team</a>
          </li>
          <li><%= link_to "Search", search_items_path, :class => "page-scroll yellow"%></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle yellow" data-toggle="dropdown"> Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to "Sign Up", signup_path, :class => "page-scroll yellow"%></li>
              <li><%= link_to "Sign in", login_path, :class => "yellow" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container move-down">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>

    <%= yield %>

</body>
</html>