p2pv2/config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root			  'static_pages#index'
  get  'howtoborrow' 	=>'static_pages#howtoborrow'
  get  'howtolend' 	=>'static_pages#howtolend'

  get 'search_items'	=>'items#index'

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'edit_user', to: 'devise/registrations#edit'
  end

  resources :users
  get 'users/index'  

  resources :items
  get 'items/index'

  resources :contracts
  get 'contracts/index'
  get 'contracts'    =>'contracts#index'
  put 'initiate'    =>'contracts#initiate'
  put 'returned'    =>'contracts#returned'

 

end

p2pv2/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def howtoborrow
  end

  def howtolend
  end
end

p2pv2/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

p2pv2/app/views/static_pages/howtoborrow.html.erb
<% provide(:title, "How To Borrow")%>

<div class="container">
	<div class ="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<div class="how-box">
				<div class="how-header text-center" >
					<h4>Getting Started</h4>
				</div>
				<div class="how-content  bg-light-grey">
				<ul>
					<li><span style="font-weight:bold"><%= link_to "Become a Member", signup_path%></span> </li>
					<li>Search our site for items you want to 
						borrow</li>
				</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>Found Something To Borrow?</h4>
				</div>
				<div class="how-content  bg-light-grey">
					<ul>
						<li>Now that you've found the item you want, register your
							interest with the owner via the item page.</li>
						<li>You will find the owners email in your account page.</li>
						<li>Over email arrange a meet up time and location that is
							convenient for you both. We recommend public places 
							to ensure everybody's safety.</li>
						</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>It's Handover Day</h4>
				</div>
				<div class="how-content  bg-light-grey">
					<ul>
						<li>Meet at the agreed upon time and date and receive the item,
							the owner will give you a code to enter into your account
							page under the correct contract.</li>  
						<li>Entering the code is confirmation that you have received the item 
							in good working order! Ensure that you are
							happy to rent the item in the current condition
							before entering the code.</li>
						<li> Use whatever you're borrowing for the agreed upon time. </li>
					</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>It's Return Day</h4>
				</div>
				<div class="how-content  bg-light-grey">
					<ul>
						<li> Return the item to its owner on the agreed upon 
							date. You will find a code on your account page for this contract.
							the owner must
							enter this in their account - this is confirmation that 
							they have received the item in good condition.</li>
						<li> Payment will be taken from your account and your 
							deposit will be returned.</li>
						<li> If you do not return the item your deposit will be taken
							and given to the owner as compensation.</li>
						
					</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>Insurance</h4>
				</div>
				<div class="how-content">
					<p>In order to keep all parties safe, we insure all
						of our borrowers. Our insurer uses
						the details kept in your smart contract to insure 
						you against harm while using an item. We also insure
						the item against damage and loss becuase we know 
						accidents can happen. We do this to keep all 
						of our members safe.</p>
				</div>
			</div>
		</div>

		<div class="col-md-3"></div>
	</div>
</div>

p2pv2/app/views/static_pages/howtolend.html.erb
<% provide(:title, "How To Lend")%>

<div class="container">
	<div class ="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<div class="how-box">
				<div class="how-header text-center" >
					<h4>Getting Started</h4>
				</div>
				<div class="how-content bg-light-grey">
				<ul>
					<li><span style="font-weight:bold"><%= link_to "Become a Member", signup_path%></span> </li>
					<li>Add any items you wish
						to rent out to the site.</li>
					<li>Items MUST be in good working order - you face
						expulsion from the page if you try to rent 
						sub-standard items. </li>
					<li>Once that's done all there is to do is wait for 
						someone to register their interest in your
						item</li>
				</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>Someone Has Registered their Interest</h4>
				</div>
				<div class="how-content bg-light-grey">
					<ul>
						<li>Anyone registering their interest in your item will receive your
							email address and get in contact with you.</li>
						<li>Over email arrange a meet up time and location that is
							convenient for you both. We recommend public places 
							to ensure everybody's safety.</li>
							
					</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>It's Handover Day</h4>
				</div>
				<div class="how-content bg-light-grey">
					<ul>	
						<li>Meet at the agreed upon time and date: remember
							to take the item with you!</li> 
						
						<li>There is a code on your user account page in the appropriate
							contract, give that to your borrower.</li>

						<li>The borrower must enter this code in their account page
							on your shared contract.</li>
						<li>This confirms that they have received the item in good working order, 
							and that it is as advertised.</li>
					</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>It's Return Day</h4>
				</div>
				<div class="how-content">
					<ul>		
						<li> When the date of return comes about, meet up once more 
							with the borrower.</li>
						<li> This time you must enter the code given to you 
							by the borrower in the correct contract on your account page
							, confirming that the item has been 
							returned in the condition in which it was lent.</li>
						<li> Payment will be sent to your account.</li>
						<li> Compensation in the form of a deposit will be
							given for any items not returned.</li>
						
					</ul>
				</div>
			</div>
			<div class="how-box">
				<div class="how-header text-center">
					<h4>Insurance</h4>
				</div>
				<div class="how-content">
					<p>In order to keep all parties safe, we insure all
						items being lent. Our insurer uses
						the details kept in the smart contract to insure 
						your items against damage and loss. </p>
				</div>
			</div>
		</div>

		<div class="col-md-3"></div>
	</div>
</div>

p2pv2/app/views/static_pages/index.html.erb
<% provide(:title, "Home")%>
<!--Bootstrap template used was "http://startbootstrap.com/template-overviews/agency/"-->
<body id="page-top" class="index">

    <!-- Header -->
    <header class="jumbotron move-up">
      <div class="container" id="hp-image">
        <div class="intro-text">

          <div class="row">
		        <div id="hp-search">

              <%= form_tag("/search_items", method: "get", :class => 'form-inline') do %>
                  <%= form_tag("/search_items", method: "get", :class => 'form-inline') do %>
                      <div class="form-group homepage-search">
                        <div class="col-md-3 homepage-search">
                          <%= text_field_tag :search, params[:search], class: 'form-control homepage-search-field', placeholder: "Item..." %>
                        </div>
                        <div class="col-md-offset-1 col-md-2 homepage-search">
                          <%= text_field_tag :search_loc, params[:search_loc], class: 'form-control homepage-search-field', placeholder: "Street, City, ..." %>
                        </div>
                        <div class="col-md-offset-2 col-md-3 homepage-search">
                          <%= submit_tag("Can I Borrow That?", :class => 'btn btn-xl text-center homepage-search-button') %>
                        </div>
                      </div>
                  <% end %>
              <% end %>

	          </div>
	         </div>

		    </div>
      </div>
    </header>
    
    
    <!-- Services Section -->
    <section id="how">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="how-heading">How It Works</h2>
                </div>
            </div>
            <div class="row text-center move-down-how">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-globe fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="how-heading">Share</h4>
                    <p class="text-muted"> Loan out your rarely used possessions to
			 your neighbours and earn some extra cash and reduce waste.  </p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-gbp fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="how-heading">Save</h4>
                    <p class="text-muted">Save money, time and resources
			by borrowing from members in your area. In doing so you'll avoid 
			a trip to the shops and a hole in your wallet.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="how-heading">Secure</h4>
                    <p class="text-muted"> Our Smart Contracts protect you! Smart
			Contracts keep everyone safe by automating the payment process 
			and providing insurance for all of our members. 
                </div>
            </div>

	    <div class="row text-center move-down-how">
            	 <div class="col-md-2" ></div>
		 <div class="col-md-3 how-button" >
			<%= link_to "How to Borrow", howtoborrow_path, :class=>"btn btn-primary btn-lg"%>
		 </div>
		 <div class="col-md-2" ></div>
		 <div class="col-md-3 how-button" >
         	 	<%= link_to "How to Lend", howtolend_path, :class=>"btn btn-primary btn-lg lend"%>
		 </div>
		 <div class="col-md-2" ></div>		

	    </div>
	</div>
    </section>



    <!-- Team Section -->
    <section id="team">
		<div class="col-md-3"></div>
		<div class="col-md-6" >
        <div id="team-container" class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Amazing Team</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        
					<%= image_tag("team_ario.jpg", alt: "Ario Aliabadi", class: "img-responsive img-circle") %>
                        <h4>Ario <br> Aliabadi</h4>
						<p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
                            
                            <li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/ario-aliabadi-b24724a2', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
					<%= image_tag("team_cataldo.jpg", alt: "Cataldo Azziriti", class: "img-responsive img-circle") %>
                        <h4>Cataldo <br> Azziriti</h4>
                        <p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
                             <li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/cataldo-azzariti-55210a2a/en', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
						<%= image_tag("team_josh.jpg", alt: "Josh Howarth", class: "img-responsive img-circle") %>
                        <h4>Josh <br> Howarth</h4>
                        <p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
                            <li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/joshua-howarth-309b4074', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <%= image_tag("team_kayla.jpg", alt: "Kayla Shapiro", class: "img-responsive img-circle") %>
                        <h4>Kayla <br> Shapiro</h4>
                        <p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
							<li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/kaylashapiro', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <%= image_tag("team_lottie.jpg", alt: "Lottie Carruthers", class: "img-responsive img-circle") %>
                        <h4>Lottie <br> Carruthers</h4>
                        <p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
                           <li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/lottie-carruthers-949456116', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
						<%= image_tag("team_veronika.jpg", alt: "Veronika Kolejakova", class: "img-responsive img-circle") %>
                        <h4>Veronika <br> Kolejakova</h4>
                        <p class="text-muted"></p>
                        <ul class="list-inline social-buttons">
                            <li><%= link_to image_tag("linkedin_logo.png", alt: "Linkedin"),
								'https://uk.linkedin.com/in/veronikakolejakova1', :target => "blank" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            </div>
            
           <!-- <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
                </div>
                -->
            </div>
            <div class="col-md-3"></div>
        </div>
    </section>

   
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span>Borrow That</span>
                </div>
                <div class="col-md-8">
                    <ul class="list-inline quicklinks">
			<li><%= link_to "How to Lend", howtolend_path%></li>
			<li><%= link_to "How To Borrow", howtoborrow_path %></li>
			<li><%= link_to "Search", search_items_path%></li>

                    </ul>
                </div>
            </div>
        </div>
    </footer>

   

    <!--&lt;!&ndash; jQuery &ndash;&gt;-->
    <!--<script src="js/jquery.js"></script>-->

    <!--&lt;!&ndash; Bootstrap Core JavaScript &ndash;&gt;-->
    <!--<script src="js/bootstrap.min.js"></script>-->

    <!--&lt;!&ndash; Plugin JavaScript &ndash;&gt;-->
    <!--<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>-->
    <!--<script src="js/classie.js"></script>-->
    <!--<script src="js/cbpAnimatedHeader.js"></script>-->

    <!--&lt;!&ndash; Contact Form JavaScript &ndash;&gt;-->
    <!--<script src="js/jqBootstrapValidation.js"></script>-->
    <!--<script src="js/contact_me.js"></script>-->

    <!--&lt;!&ndash; Custom Theme JavaScript &ndash;&gt;-->
    <!--<script src="js/agency.js"></script>-->