p2pv2/config/routes.rb
Rails.application.routes.draw do

	
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root			  'static_pages#index'
  get  'howtoborrow' 	=>'static_pages#howtoborrow'
  get  'howtolend' 	=>'static_pages#howtolend'

  get 'search_items'	=>'items#index'

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'edit_user', to: 'devise/registrations#edit'
  end

  resources :users
  get 'users/index'  

  resources :items
  get 'items/index'

  resources :contracts
  get 'contracts/index'
  get 'contracts'    =>'contracts#index'
  put 'initiate'    =>'contracts#initiate'
  put 'returned'    =>'contracts#returned'

 

end

p2pv2/app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user
  validates :user, presence: true

  # BEGIN Item entries in the database MUST have these entries valid
  validates :name, presence: true, length: { maximum: 255 }
  validates :location, presence: true, length: { maximum: 50 }

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def self.search(search)            # find the items that contain the search word in their name, category or model
    where("lower(name || category || model) LIKE ?", "%#{search.downcase}%")
  end

  def address                       # return location of the item as address
    "#{location}"
  end

  def full_street_address
    "#{location}"
  end
end

p2pv2/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, :set_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /items
  # GET /items.json
  # if search parameters are present, use them to narrow the list of the items
  def index
    @items = Item.all
    if params[:search_loc].present? and params[:search]
      @items = Item.search(params[:search]).near(params[:search_loc], 200)
    elsif params[:search_loc].present?
      @items = Item.near(params[:search_loc], 200)
    elsif params[:search]
      @items = Item.search(params[:search])
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    if user_signed_in?
      @item = Item.new
    else
      flash[:danger] = "You should log in before adding an item."
      redirect_to login_path
    end
  end

  # GET /items/1/edit
  def edit
    # if @item.user_id == @current_user.id
    # end
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:id, :name, :category, :model, :age, :location, :min_loan_period, :max_loan_period, :deposit, :rental_rate, :user_id)
    end
end

p2pv2/app/helpers/items_helper.rb
module ItemsHelper
end

p2pv2/app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item" } do |f| %>

  <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Item's name*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category) %>
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :model, :class => 'form-control' %>
    </div>
    <%=f.error_span(:model) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  <div class="form-group">
    <%= f.label :location, "Location*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control', placeholder: "Street, City, 2-letter country code" %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :min_loan_period, "Minimum loan period (day)*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :min_loan_period, :class => 'form-control' %>
    </div>
    <%=f.error_span(:min_loan_period) %>
  </div>
  <div class="form-group">
    <%= f.label :max_loan_period, "Maxloan period (days)*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :max_loan_period, :class => 'form-control' %>
    </div>
    <%=f.error_span(:max_loan_period) %>
  </div>
  <div class="form-group">
    <%= f.label :deposit, "Deposit (£)*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :deposit, :class => 'form-control' %>
    </div>
    <%=f.error_span(:deposit) %>
  </div>
  <div class="form-group">
    <%= f.label :rental_rate, "Rental rate (£/day)*", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rental_rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rental_rate) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

p2pv2/app/views/items/edit.html.erb
<div class="container">
  <%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

p2pv2/app/views/items/index.html.erb
<div class="container">
 <%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
 <%= form_tag("/search_items", method: "get", :class => 'form-inline') do %>
     <div class="form-group">
       <%= label_tag("I'm looking for") %>
       <%= text_field_tag :search, params[:search], class: 'form-control' %>
       <%= label_tag("near") %>
       <%= text_field_tag :search_loc, params[:search_loc], class: 'form-control' %>
       <%= submit_tag("Search", :class => 'btn btn-primary') %>
     </div>
 <% end %>
 <% if @items.present? %>
     <br><p><b>These items are present</b></p>
     <table class="table table-striped">
       <thead>
       <tr>
         <th><%= model_class.human_attribute_name(:id) %></th>
         <th><%= model_class.human_attribute_name(:name) %></th>
         <th><%= model_class.human_attribute_name(:category) %></th>
         <th><%= model_class.human_attribute_name(:model) %></th>
         <th><%= model_class.human_attribute_name(:age) %></th>
         <th><%= model_class.human_attribute_name(:location) %></th>
         <th><%= model_class.human_attribute_name(:min_loan_period) %></th>
         <th><%= model_class.human_attribute_name(:max_loan_period) %></th>
         <th><%= model_class.human_attribute_name(:deposit) %> (£)</th>
         <th><%= "Loan Amount (£)" %></th>
         <th><%= "Distance (miles)" %></th>
       </tr>
       </thead>
       <tbody>
       <% @items.each do |item| %>
           <tr>
             <td><b><%= link_to item.id, item_path(item) %></b></td>
             <td><b><%= link_to item.name.upcase, item_path(item) %></b></td>
             <td><%= item.category %></td>
             <td><%= item.model %></td>
             <td><%= item.age %></td>
             <td><%= item.location %></td>
             <td><%= item.min_loan_period %></td>
             <td><%= item.max_loan_period %></td>
             <td><%= item.deposit %></td>
             <td><%= item.rental_rate %></td>
             <td>
               <% if params[:search_loc].present? %>
                   <%= number_with_precision(item.distance_from(Geocoder.coordinates("#{params[:search_loc].to_s}")), precision: 1) %>
               <% else %>
                   <%= "N/A" %>
               <% end %>
             </td>
           </tr>
       <% end %>
       </tbody>
     </table>

 <% elsif params[:search_loc].present? %>
     <br><p><b>Unfortunately, there are no such items within 200 miles of you.</b></p>
 <% else %>
     <br><p><b>Unfortunately, there are no items containing the term</b> <%= params[:search] %>.</p>
 <% end %>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_item_path,
              :class => 'btn btn-primary' %>

</div>

p2pv2/app/views/items/new.html.erb
<div class="container">
 <%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

p2pv2/app/views/items/show.html.erb
<div class="container">
<%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @item.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
    <dd><%= @item.category %></dd>
    <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
    <dd><%= @item.model %></dd>
    <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
    <dd><%= @item.age %></dd>
    <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
    <dd><%= @item.location %></dd>
    <dt><strong><%= model_class.human_attribute_name(:min_loan_period) %>:</strong></dt>
    <dd><%= @item.min_loan_period %></dd>
    <dt><strong><%= model_class.human_attribute_name(:max_loan_period) %>:</strong></dt>
    <dd><%= @item.max_loan_period %></dd>
    <dt><strong><%= model_class.human_attribute_name(:deposit) %> (£):</strong></dt>
    <dd><%= @item.deposit %></dd>
    <dt><strong>Loan Amount (£):</strong></dt>
    <dd><%= @item.rental_rate %></dd>
  </dl>

  <%= link_to t('.back', :default => t("helpers.links.back")),
                items_path, :class => 'btn btn-default'  %>
  <% if user_signed_in? and @item.user_id == current_user.id %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_item_path(@item), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  item_path(@item),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  <% end %>
                
  <% if user_signed_in? %>
      <%= link_to 'Inquire', {:controller => "contracts", :action => "new",
                :item_id => @item.id, 
                :lender_id => @item.user_id,
                :deposit => @item.deposit,
                :rental_rate => @item.rental_rate,
                :name => @item.name,
                :min_loan_period => @item.min_loan_period,
                :max_loan_period => @item.max_loan_period}, 
                :class => 'btn btn-default' %>
  <% elsif !user_signed_in? %>
      <%= link_to 'Login to Inquire', login_path, :class => 'btn btn-default' %>
  <% end %>

</div>